"""Export adapters — outbound protocol delivery.

After resynthesis, the updated protocol needs to reach whatever system
consumes it. Export adapters format the protocol text for different
targets.
"""

from __future__ import annotations

import logging
from pathlib import Path

from ..config import Config

logger = logging.getLogger(__name__)


def export_raw(config: Config, protocol_text: str, path: Path) -> None:
    """Write protocol text to a file with a metadata header.

    Creates parent directories as needed.
    """
    header = (
        f"<!-- protolab v{config.protocol_version} -->\n"
        f"<!-- source: {config.protocol_path} -->\n\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + protocol_text)
    logger.debug("Exported raw protocol to %s", path)


def export_promptfoo(config: Config, protocol_text: str) -> str:
    """Generate a Promptfoo-compatible YAML config snippet.

    Returns a YAML string with the protocol as the system prompt,
    ready to paste into a ``promptfooconfig.yaml`` file.
    """
    # Escape the protocol text for YAML block scalar
    # Using literal block scalar (|) preserves newlines
    indented = "\n".join(f"    {line}" for line in protocol_text.splitlines())
    yaml_text = (
        f"# Generated by protolab (v{config.protocol_version})\n"
        f"prompts:\n"
        f"  - id: protolab-protocol\n"
        f"    raw: |\n"
        f"{indented}\n"
    )
    logger.debug("Generated Promptfoo export snippet")
    return yaml_text
